### ISSUE TITLE
Amazon-Product price yab(Price)

### ISSUE THREAD

**Issue by ashkmb** [ashkankamyab/xyab#2]
### Description:
Add a python script which gets product uri as an argument and parse the Price of this.

**Comment by martinh-dev** [comment]
Hey @ashkankamyab, I would like to work on this issue. Pleas assign it to me. Thanks.

**Comment by ashkmb** [comment]
@martinh-dev 
Sure, Go ahead 👍 

Some friendly remarks:

    1. Please use function and call_backs if needed.
    2. Please use `bs4` and `requests` for parsing the html source_code.

A Friendly hint
You can take a look at [camelcamelcamel.org](https://camelcamelcamel.com/)
You may take the advantage of the Product Id after https://de.camelcamelcamel.com/product/<id>


Happy coding. 🍺

**Comment by martinh-dev** [comment]
Running the Docker file runs into an error. Do you have some advices to get started?

**Comment by ashkmb** [comment]
> Running the Docker file runs into an error. Do you have some advices to get started?

Well you should give me the error message buddy.

**Comment by jp2373** [comment]
I would also like to work on if it's possible!

**Comment by martinh-dev** [comment]
> > Running the Docker file runs into an error. Do you have some advices to get started?
> 
> Well you should give me the error message buddy.

docker build --rm -f "Dockerfile" -t xyab:latest "."
[+] Building 0.0s (0/1)                                                                                                                                                                                       
source /Users/martinhoffmann/opt/anaconda3/bin/activate
[+] Building 1.5s (7/14)                                                                                                                                                                                      
 => [internal] load .dockerignore                                                                                                                                                                        0.0s
 => => transferring context: 2B                                                                                                                                                                          0.0s
 => [internal] load build definition from Dockerfile                                                                                                                                                     0.0s
 => => transferring dockerfile: 997B                                                                                                                                                                     0.0s
 => [internal] load metadata for docker.io/library/ubuntu:latest                                                                                                                                         1.2s
 => [1/10] FROM docker.io/library/ubuntu@sha256:bc2f7250f69267c9c6b66d7b6a81a54d3878bb85f1ebb5f951c896d13e6ba537                                                                                         0.0s
 => [internal] load build context                                                                                                                                                                        0.0s
 => => transferring context: 1.88kB                                                                                                                                                                      0.0s
 => CACHED [2/10] RUN apt-get update -qqq && apt-get update -qqqy                                                                                                                                        0.0s
 => ERROR [3/10] RUN apt-get install -qqgity         locales         build-essential         libssl-dev         libffi-dev         python3         python3-pip         python3-dev                       0.2s
------
 > [3/10] RUN apt-get install -qqgity         locales         build-essential         libssl-dev         libffi-dev         python3         python3-pip         python3-dev:
#6 0.181 E: Command line option 'g' [from -qqgity] is not understood in combination with the other options.
------
failed to solve with frontend dockerfile.v0: failed to build LLB: executor failed running [/bin/sh -c apt-get install -qqgity         locales         build-essential         libssl-dev         libffi-dev         python3         python3-pip         python3-dev]: runc did not terminate sucessfully
martinhoffmann@Martins-MBP xyab % source /Users/martinhoffmann/opt/anaconda3/bin/activate
(base) martinhoffmann@Martins-MBP xyab % conda activate base

**Comment by ashkmb** [comment]
> failed to solve with frontend dockerfile.v0: failed to build LLB: executor failed running [/bin/sh -c apt-get install -qqgity         locales         build-essential         libssl-dev         libffi-dev         python3         python3-pip         python3-dev]: 


Well. This is true.
In order to fix it you should edit the dockerfile.

``` 
apt-get install -qqy [a list of packages]
```

May I ask you please open an issue for it?

**Comment by ashkmb** [comment]
I have fixed it. 
Cheers :beer:

**Comment by martinh-dev** [comment]
Thank you very much. But now I am getting an other error:

File "main.py", line 45, in <module>
    updater.start_polling()
  File "/usr/local/lib/python3.8/dist-packages/telegram/ext/updater.py", line 259, in start_polling
    self.job_queue.start()
  File "/usr/local/lib/python3.8/dist-packages/telegram/ext/jobqueue.py", line 446, in start
    name="Bot:{}:job_queue".format(self._dispatcher.bot.id))
  File "/usr/local/lib/python3.8/dist-packages/telegram/bot.py", line 51, in decorator
    self.get_me()
  File "<decorator-gen-1>", line 2, in get_me
  File "/usr/local/lib/python3.8/dist-packages/telegram/bot.py", line 67, in decorator
    result = func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/telegram/bot.py", line 289, in get_me
    result = self._request.get(url, timeout=timeout)
  File "/usr/local/lib/python3.8/dist-packages/telegram/utils/request.py", line 276, in get
    result = self._request_wrapper('GET', url, **urlopen_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/telegram/utils/request.py", line 242, in _request_wrapper
    raise Unauthorized(message)
telegram.error.Unauthorized: Unauthorized

**Comment by ashkmb** [comment]
Well now, you need to apply for your own telegram bot credential. 
please refer to [this page](https://core.telegram.org/bots) . Basically you should send a message to @botfather.
But you don't need this for now, I suggest to create a new pyenv using `pip install -r requirements.txt`. This will install all dependencies on your local machine. We can create a new issue for dockerzing your code when you are done with it :)

**Comment by ashkmb** [comment]
Further improvement on #6 
This issue can be closed.
