### ISSUE TITLE
Regex: extract product ID of an Amazon Product url.

### ISSUE THREAD

**Issue by ashkmb** [ashkankamyab/xyab#6]
We need to improve the `getPrice()` function or APPLY call back function which gets amazon url and extract the product ID from it. `getPrice()` is within getPriceFromAmazon.py .

e.G:
url: https://www.amazon.de/dp/B07D4NBPBC/?coliid=I319WKCKA7BBFQ&colid=1XEYCRQZQ0TJB&psc=1
PID: B07D4NBPBC

this will be implemented within a script call getPriceFromAmazon. See #5

**Comment by martinh-dev** [comment]
As allready mentioned, I would like to work at this issue too. Please assign it to me. Thanks.

**Comment by ashkmb** [comment]
> As allready mentioned, I would like to work at this issue too. Please assign it to me. Thanks.

Done.
Let me know if I can help.
