### ISSUE TITLE
Logic: Compare the current amazon price and send notification if it bellower than 20 Precent

### ISSUE THREAD

**Issue by ashkmb** [ashkankamyab/xyab#8]
We would like to add auto notifier to the getPriceFromAmazon.py. This should conduct as follow:

- It checks the Price every 12 Hours (As on Prime-Day prices get update every 12 Hour
- It compare the actual price with the original price and if the cut rate:
    - Smaller than 13% sends an email.
    - Greater than 13% and smaller than 20% sends WhatsApp/Telegram Message
    - Equals or greater than 20 % sends sms.

### Some friendly hints:
For SMS and WhatsApp please refer to this [link](https://www.twilio.com/)
For Telegram Message Please refer to this [link](https://core.telegram.org/bots/api)
For email you should have a Mail server installed and this [snippet](https://github.com/ashkankamyab/SysPy/blob/master/Python/smtp.py) is handy

**Comment by roterhut** [comment]
Please assign this to me

**Comment by ashkmb** [comment]
@roterhut Done
